name: Create Archive

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'scouting-improvements-child-${{ github.ref_name }}.zip'

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: 'scouting-improvements-child-${{ github.ref_name }}.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true